"""add_all_tables

Revision ID: 3a7a59af0546
Revises: 5cb43c3bfccd
Create Date: 2026-04-06 19:08:59.434530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7a59af0546'
down_revision: Union[str, Sequence[str], None] = '5cb43c3bfccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_refresh_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_refresh_token_user_id'), 'auth_refresh_token', ['user_id'], unique=False)
    op.create_table('campaign_deliverable',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('deliverable_type', sa.Enum('reel', 'post', 'story', 'yt_video', 'shorts', name='content_type'), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_days_after_accept', sa.SmallInteger(), nullable=False),
    sa.Column('revision_limit', sa.SmallInteger(), nullable=False),
    sa.Column('milestone_pct', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('due_days_after_accept >= 0', name='check_due_days'),
    sa.CheckConstraint('milestone_pct >= 0 AND milestone_pct <= 100', name='check_milestone_pct'),
    sa.CheckConstraint('revision_limit >= 0', name='check_revision_limit'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_deliverable_campaign_id'), 'campaign_deliverable', ['campaign_id'], unique=False)
    op.create_table('campaign_submission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('deliverable_id', sa.UUID(), nullable=False),
    sa.Column('submission_url', sa.String(length=1000), nullable=False),
    sa.Column('url_valid', sa.Boolean(), nullable=True),
    sa.Column('revision_number', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('under_review', 'approved', 'revision_requested', 'disputed', name='submission_status'), nullable=False),
    sa.Column('brand_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['campaign_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['campaign_deliverable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'deliverable_id', 'revision_number', name='unique_submission_revision')
    )
    op.create_index(op.f('ix_campaign_submission_application_id'), 'campaign_submission', ['application_id'], unique=False)
    op.create_index(op.f('ix_campaign_submission_deliverable_id'), 'campaign_submission', ['deliverable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_submission_deliverable_id'), table_name='campaign_submission')
    op.drop_index(op.f('ix_campaign_submission_application_id'), table_name='campaign_submission')
    op.drop_table('campaign_submission')
    op.drop_index(op.f('ix_campaign_deliverable_campaign_id'), table_name='campaign_deliverable')
    op.drop_table('campaign_deliverable')
    op.drop_index(op.f('ix_auth_refresh_token_user_id'), table_name='auth_refresh_token')
    op.drop_table('auth_refresh_token')
    # ### end Alembic commands ###
