"""create initial tables

Revision ID: b87e03388321
Revises: 61bef972f131
Create Date: 2026-03-27 19:45:33.248457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b87e03388321'
down_revision: Union[str, Sequence[str], None] = '61bef972f131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'brand', 'influencer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified_phone', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('brand_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('verified_badge', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_campaigns_run', sa.Integer(), nullable=True),
    sa.Column('onboarding_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profile_user_id'), 'brand_profile', ['user_id'], unique=True)
    op.create_table('influencer_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('niche', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('follower_tier', sa.String(), nullable=True),
    sa.Column('total_followers', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Numeric(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('profile_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_profile_user_id'), 'influencer_profile', ['user_id'], unique=True)
    op.create_table('campaign',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niche_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('min_followers', sa.Integer(), nullable=True),
    sa.Column('max_followers', sa.Integer(), nullable=True),
    sa.Column('budget_total', sa.Numeric(), nullable=True),
    sa.Column('budget_per_slot', sa.Numeric(), nullable=True),
    sa.Column('max_slots', sa.SmallInteger(), nullable=True),
    sa.Column('slots_filled', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'cancelled', name='campaign_status'), server_default='draft', nullable=False),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_slots IS NULL OR slots_filled IS NULL OR slots_filled <= max_slots', name='campaign_slots_filled_le_max_slots'),
    sa.CheckConstraint('min_followers IS NULL OR max_followers IS NULL OR min_followers <= max_followers', name='campaign_min_le_max_followers'),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_brand_id'), 'campaign', ['brand_id'], unique=False)
    op.create_table('influencer_social_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'youtube', 'tiktok', name='social_platform'), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Numeric(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_social_account_influencer_id'), 'influencer_social_account', ['influencer_id'], unique=False)
    op.create_table('campaign_application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('quoted_price', sa.Numeric(), nullable=True),
    sa.Column('ai_match_score', sa.Numeric(), nullable=True),
    sa.Column('application_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', name='application_status'), server_default='pending', nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'influencer_id', name='uq_campaign_application_campaign_influencer')
    )
    op.create_index(op.f('ix_campaign_application_campaign_id'), 'campaign_application', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_application_influencer_id'), 'campaign_application', ['influencer_id'], unique=False)
    op.create_table('campaign_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_message_campaign_id'), 'campaign_message', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_message_recipient_id'), 'campaign_message', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_campaign_message_sender_id'), 'campaign_message', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_message_sender_id'), table_name='campaign_message')
    op.drop_index(op.f('ix_campaign_message_recipient_id'), table_name='campaign_message')
    op.drop_index(op.f('ix_campaign_message_campaign_id'), table_name='campaign_message')
    op.drop_table('campaign_message')
    op.drop_index(op.f('ix_campaign_application_influencer_id'), table_name='campaign_application')
    op.drop_index(op.f('ix_campaign_application_campaign_id'), table_name='campaign_application')
    op.drop_table('campaign_application')
    op.drop_index(op.f('ix_influencer_social_account_influencer_id'), table_name='influencer_social_account')
    op.drop_table('influencer_social_account')
    op.drop_index(op.f('ix_campaign_brand_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_influencer_profile_user_id'), table_name='influencer_profile')
    op.drop_table('influencer_profile')
    op.drop_index(op.f('ix_brand_profile_user_id'), table_name='brand_profile')
    op.drop_table('brand_profile')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
